'use client'
import { useSelector } from 'react-redux'
import type { Metadata } from 'next'

import Navbar from '../shared/Navbar'
import Footer from '../shared/Footer'
import { RootState } from '@/store/store'
export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function VendorLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const vendor = useSelector((state: RootState) => state.vendor.vendor)
  const isAuthenticated = !!vendor
  return (
    <section lang='en'>
      <Navbar role='vendor' isAuthenticated={isAuthenticated} />
      {children}
      <Footer />
    </section>
  )
}
