'use client'
import { useSelector } from 'react-redux'
import type { Metadata } from 'next'

import Navbar from '../shared/Navbar'
import Footer from '../shared/Footer'
import { RootState } from '@/store/store'
export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function VendorLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const vendor = useSelector((state: RootState) => state.vendor.vendor)
  const isAuthenticated = !!vendor
  return (
    <section lang='en' className='min-h-screen flex flex-col bg-gray-50/50'>
      <Navbar role='vendor' isAuthenticated={isAuthenticated} />
      <main className='flex-1 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8'>
        {children}
      </main>
      <Footer />
    </section>
  )
}
